# Generated by Django 3.2.15 on 2022-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApp', '0003_alter_candidatemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemodel',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
